name: Test Ubuntu

on:  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8.18', '3.9.21', '3.10.15', '3.11.11', '3.12.9', '3.13.2']
        cxx: [g++, clang++]
        std: [c++98, c++11, c++14, c++17]
        include:
          # Add the appropriate docker image for each compiler.
          # The images from teeks99/boost-python-test already have boost::python
          # pre-reqs installed, see:
          # https://github.com/teeks99/boost-python-test-docker
          - cxx: clang++
            docker-img: teeks99/boost-python-test:clang-12_1.76.0
          - cxx: g++
            docker-img: teeks99/boost-python-test:gcc-10_1.76.0

    container:
      image: ${{ matrix.docker-img }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: build
      run: |
        python --version
        ${{ matrix.cxx }} --version
        faber -v
        sed -e "s/\$PYTHON/${{ matrix.python }}/g" .ci/faber > ~/.faber
        faber \
          --with-boost-include=${BOOST_PY_DEPS} \
          --builddir=build \
          cxx.name=${{ matrix.cxx }} \
          cxxflags=-std=${{ matrix.std }} \
          cppflags=-std=${{ matrix.std }} \
          -j`nproc`
    - name: test
      run: |
        faber \
          --with-boost-include=${BOOST_PY_DEPS} \
          --builddir=build \
          cxx.name=${{ matrix.cxx }} \
          cxxflags=-std=${{ matrix.std }} \
          cppflags=-std=${{ matrix.std }} \
          -j`nproc` \
          test.report
